### ISSUE TITLE
point cloud viewer does not load any points until first movement command is issued

### ISSUE THREAD

**Issue by bochen87** [googlecartographer/point_cloud_viewer#18]
Hi, 

I figured out in the meanwhile how to use the assets_writer_main to get the 3D points. I am using your point cloud viewer now to display the 3D octree. I've built the octree using the build_octree and ran the viewer on the octree folder. However, as you can see from the screen shot attached in the google drive link, it's all black. I also uploaded the trajectory file and generated 3D points file. I used the example 3D bagfile under https://storage.googleapis.com/cartographer-public-data/bags/backpack_3d/b3-2016-04-05-14-14-00.bag

Here is my google drive link with the relevant files for reproduction:
https://drive.google.com/drive/folders/0B7YeGrYWwtQqNU1QOHp2V1FLRkU?usp=sharing

**Comment by SirVer** [comment]
Try clicking and dragging a bit. The viewer is not automatically loading until the first movement is made. This in itself is a bug of course.

**Comment by jpapon** [comment]
It's all black for me as well - though the terminal I launched the viewer in gives messages like this:
Got 51 nodes with 308516 points (38.53381ms).
Got 51 nodes with 282775 points (34.249233ms).
Got 28 nodes with 240495 points (26.963284ms).

I may be using it incorrectly though - I just loaded the octree folder using viewer, and then opened http://localhost:5433/ in a browser (chrome). Is that correct?

**Comment by SirVer** [comment]
@jpapon My guess is that all your points are black. 

The tool is clearly loading stuff and you should see it too, since the camera looks at the origin. But if all your points are nearly (or completely) black, you will not see anything. You can take a look in your .ply file with a hex editor - it contains 12 bytes `x, y, z` and then 3 bytes for RGB for each point.

**Comment by jpapon** [comment]
@SirVer That does appear to be the case. It may have been the case for @bochen87 as well.
Might be a nice feature to add to colorize points by different filters (e.g. z-axis).

On a related note - I'm currently using the a pipeline like this in my assets_writer (with Velodyne data as input):
```
pipeline = {
    {
      action = "min_max_range_filter",
      min_range = 1.5,
      max_range = 50.0,
    },
    {
      action = "voxel_filter_and_remove_moving_objects",
      voxel_size = VOXEL_SIZE,
    },
    {
      action = "intensity_to_color",
      min_intensity = 0,
      max_intensity = 100,
    },
   {
      action = "write_ply",
      filename = OUTPUT_STEM .. "_" .. "points.ply",
    },
}

```

but as you suggested, it's resulting in the points being black. Do you think that is due to the voxel filter not averaging intensities correctly?

**Comment by SirVer** [comment]
> Might be a nice feature to add to colorize points by different filters (e.g. z-axis).

Yes, that would be cool! I think generally it would be cool if the viewer could deal with other properties better and also provide more color options. Are you interested in implementing this?

> Do you think that is due to the voxel filter not averaging intensities correctly?

It could be that the voxel filter is not handing intensities through. Thinking about this now, it seems very likely actually. Do you get colors if you remove this step?

**Comment by jpapon** [comment]
The problem was actually in assets_writer_main.cc in cartographer_ros. I've submitted a quick fix for it in googlecartographer/cartographer_ros#321

I can work on adding the colorizing at some point - I would likely just copy the functionality from PCL's pcl_viewer though.

**Comment by SirVer** [comment]
> I can work on adding the colorizing at some point - I would likely just copy the functionality from PCL's pcl_viewer though.

I think this should go into the client, i.e. the point cloud viewer itself - at least if it is easy to compute on the fly.
